/**
 * Generated by Gas3 v3.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (StockPrice.as).
 */

package org.graniteds.tutorial.feed.entities {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.math.BigDecimal;

    [Bindable]
    public class StockPriceBase implements IExternalizable {

        public function StockPriceBase() {
        }

        private var _name:String;
        private var _price:BigDecimal;

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set price(value:BigDecimal):void {
            _price = value;
        }
        public function get price():BigDecimal {
            return _price;
        }

        public function readExternal(input:IDataInput):void {
            _name = input.readObject() as String;
            _price = input.readObject() as BigDecimal;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_name);
            output.writeObject(_price);
        }
    }
}